import {test,expect} from '@playwright/test';
test('real case, evidence recomputation, parity filters, notes, and linked comparison',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/investigations/newby-island');await expect(page.locator('.selection-scope')).toContainText('3 selected observations');
 await page.getByRole('button',{name:/ESTABLISHED/}).click();
 for(const [date,n] of [['26 Sept 2024',2],['7 Aug 2024',1],['3 Aug 2024',0]] as const){await page.getByRole('checkbox',{name:`Include ${date} in brief`}).uncheck();await expect(page.locator('.selection-scope')).toContainText(`${n} selected observations`);}
 await expect(page.getByText('No observations are selected for this brief.',{exact:true}).first()).toBeVisible();
 await page.getByRole('checkbox',{name:'Include 3 Aug 2024 in brief'}).check();await expect(page.locator('.quoted-finding')).toContainText('does not establish repeated');await page.getByRole('button',{name:'Close',exact:true}).click();
 await page.locator('.date-filter-disclosure summary').click();await page.getByLabel('Filter observations from').fill('2025-01-01');await expect(page.getByText('No observations in this date range',{exact:true})).toBeVisible();await page.getByRole('tab',{name:'Evidence list'}).click();await expect(page.getByText('No observations in this date range',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Reset dates',exact:true}).click();await expect(page.locator('.observation-row')).toHaveCount(3);
 await page.getByRole('button',{name:'Add a note On this device'}).click();await page.getByLabel('Your notes',{exact:true}).fill('Private test note <b>plain text</b>');await page.getByRole('button',{name:'Save notes',exact:true}).click();await page.reload();await page.getByRole('button',{name:'Edit your notes On this device'}).click();await expect(page.getByLabel('Your notes',{exact:true})).toHaveValue('Private test note <b>plain text</b>');await page.getByRole('button',{name:'Close',exact:true}).click();
 await page.getByRole('button',{name:/Can these figures be compared/}).click();await expect(page.getByText('7,954.5 metric tonnes CH₄',{exact:true})).toBeVisible();await expect(page.getByText('Numerical comparison withheld',{exact:true})).toBeVisible();await expect(page.getByText('Landfill or composting?',{exact:true})).toBeVisible();expect(errors).toEqual([]);
});
test('search resolves real geography and distinguishes absent dataset coverage',async({page})=>{
 await page.goto('/explore');await page.getByRole('button',{name:'Find a city or US ZIP'}).click();const search=page.getByRole('textbox',{name:'City, region, or US ZIP code'});await search.fill('Denver');await page.getByRole('button',{name:/Denver.*United States/}).click();await expect(page.getByText('No included observations nearby',{exact:true})).toBeVisible();await expect(page).toHaveURL(/\/places\//);await page.locator('.header-place').click();await search.fill('95035');await page.getByRole('button',{name:/Milpitas.*95035/}).click();await expect(page.locator('.place-result-card').filter({hasText:'Nearest included origin'})).toBeVisible();
});
test('snapshot failure has a retry and does not substitute mock evidence',async({page})=>{await page.route('**/snapshot.json',r=>r.abort());await page.goto('/explore');await expect(page.getByRole('heading',{name:'The snapshot is unavailable'})).toBeVisible();await expect(page.getByRole('button',{name:'Try again'})).toBeVisible();await expect(page.locator('canvas')).toHaveCount(0);});
test('unavailable basemap preserves the dated raster and discloses the failure',async({page})=>{await page.route('https://tiles.openfreemap.org/**',r=>r.abort());await page.goto('/explore');await expect(page.getByText('Basemap unavailable. Showing the georeferenced observations.')).toBeVisible();await expect(page.locator('.map-canvas')).toBeVisible();});
test('responsive workspace never overflows horizontally',async({page})=>{for(const width of [1672,1024,768,390]){await page.setViewportSize({width,height:960});await page.goto('/investigations/newby-island');await expect(page.getByRole('heading',{name:'Newby Island, California',exact:true,level:1})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}});
test('real PDF and ZIP agree, retain provenance, and verify every packaged hash',async({page})=>{
 const {unzipSync,strFromU8}=await import('fflate');const {createHash}=await import('node:crypto');const {readFile}=await import('node:fs/promises');
 await page.goto('/investigations/newby-island');await page.getByRole('button',{name:'Create investigation brief'}).click();await page.getByRole('button',{name:'Generate PDF preview'}).click();await expect(page.getByRole('link',{name:'Download PDF',exact:true})).toBeVisible();const fingerprint=(await page.locator('.brief-sheet .body-note code').textContent())!.slice(0,20);
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download evidence ZIP',exact:true}).click();const file=await download;const path=await file.path();const files=unzipSync(await readFile(path!));const manifest=JSON.parse(strFromU8(files['manifest.json']));
 expect(manifest.evidenceFingerprint.startsWith(fingerprint)).toBe(true);expect(manifest.selectedIds).toHaveLength(3);expect(manifest.canonicalInput.includeNotes).toBe(false);expect(manifest.canonicalInput.notes).toBe('');expect(strFromU8(files['brief.pdf'].slice(0,5))).toBe('%PDF-');expect(files['inventory.json']).toBeDefined();expect(files['infrastructure.json']).toBeDefined();
 for(const f of manifest.files)expect(createHash('sha256').update(files[f.path]).digest('hex')).toBe(f.sha256);
 expect(strFromU8(files['manifest.sha256']).split(' ')[0]).toBe(createHash('sha256').update(files['manifest.json']).digest('hex'));
 await page.getByRole('checkbox',{name:'Include 26 Sept 2024 in brief'}).uncheck();await expect(page.getByRole('link',{name:'Download PDF',exact:true})).toHaveCount(0);
});
