'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {ArrowRight,Info,LoaderCircle,MapPin,Search} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import type {Snapshot} from '@/lib/plume/types';
import {distanceKm} from '@/lib/plume/evidence';
type Place={id:string;name:string;ascii?:string;postal?:string;country:string;admin:string;location:[number,number];population:number;type:string};
export function PlaceSearch({snapshot}:{snapshot:Snapshot;onNotice?:(text:string)=>void}){
 const [query,setQuery]=useState(''),[radius,setRadius]=useState('25'),[results,setResults]=useState<Place[]>([]),[place,setPlace]=useState<Place>(),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const worker=useRef<Worker|null>(null),request=useRef(0);
 useEffect(()=>{const w=new Worker('/workers/search.js',{type:'module'});worker.current=w;w.onmessage=e=>{if(e.data.request!==request.current)return;setLoading(false);setError(e.data.error||'');setResults(e.data.results||[]);};w.onerror=()=>{setLoading(false);setError('Place lookup is unavailable. Included investigations remain accessible.');};return()=>w.terminate();},[]);
 useEffect(()=>{const id=++request.current;if(query.trim().length<2){setResults([]);setLoading(false);return;}setLoading(true);const timer=setTimeout(()=>worker.current?.postMessage({query,request:id,origin:location.origin}),220);return()=>clearTimeout(timer);},[query]);
 const cases=place?snapshot.cases.map(c=>({c,distance:Math.min(...snapshot.observations.filter(o=>c.observationIds.includes(o.id)).map(o=>distanceKm(place.location,o.location)))})).filter(x=>x.distance<=Number(radius)).sort((a,b)=>a.distance-b.distance):[];
 return <div className="place-search-content"><label className="search-box"><Search size={18}/><input value={query} onChange={e=>{setQuery(e.target.value);setPlace(undefined);}} maxLength={120} placeholder="City, region, or US ZIP code" aria-label="City, region, or US ZIP code"/></label><p className="body-note">Major world cities, regional centers, and US ZIP centroids. The satellite snapshot covers only the included investigations.</p>{loading&&<p className="loading-line" role="status"><LoaderCircle className="spin" size={15}/> Looking up the place…</p>}{error&&<p role="alert" className="attention-box">{error}</p>}{!place&&results.map(p=><button key={p.id} className="place-option" onClick={()=>setPlace(p)}><MapPin size={17}/><span><strong>{p.name}{p.postal?' · '+p.postal:''}</strong><small>{p.admin} · {p.country} · {p.type}</small></span><ArrowRight size={14}/></button>)}{!place&&!loading&&query.length>=2&&!results.length&&!error&&<div className="empty-state"><h3>Place not resolved</h3><p>Try a major city, a regional center, or a US ZIP code. This lookup does not include every place.</p></div>}{place&&<><div className="place-selected"><MapPin/><h3>{place.name}{place.postal?' '+place.postal:''}</h3><p>{place.admin}, {place.country} · approximate center</p></div><label className="radius-label">Search distance from this place’s center<Select value={radius} onValueChange={setRadius}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['10','25','50','100'].map(r=><SelectItem key={r} value={r}>Within {r} km</SelectItem>)}</SelectContent></Select></label>{cases.length?cases.map(({c,distance})=><Link href={'/investigations/'+c.id} className="place-option" key={c.id}><span><strong>{c.place}</strong><small>Nearest included origin: {distance.toFixed(1)} km</small></span><ArrowRight size={16}/></Link>):<div className="empty-state"><Info/><h3>No included observations nearby</h3><p>No published observations in this dataset for the selected area. This does not establish that methane emissions are absent.</p><button onClick={()=>{setPlace(undefined);setQuery('');}}>Reset search</button></div>}<h3 className="sheet-section-title">Explore a separately located example</h3>{snapshot.cases.map(c=><Link className="text-link" href={'/investigations/'+c.id} key={c.id}>{c.place} <ArrowRight size={14}/></Link>)}</>}<p className="data-credit">Place data: <a href="https://www.geonames.org/" target="_blank" rel="noreferrer">GeoNames</a>, CC BY 4.0. Geographic distance is not exposure or source attribution.</p></div>;
}
