'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import Link from 'next/link';
import dynamic from 'next/dynamic';
import {ArrowLeft,ArrowRight,ArrowUpRight,Bookmark,Check,CheckCheck,ChevronLeft,ChevronRight,Download,ExternalLink,FileText,Info,Layers3,List,LoaderCircle,Map as MapIcon,MapPin,Pause,Play,Search,Share2,ShieldCheck,SlidersHorizontal,SplitSquareHorizontal,StickyNote,ChartNoAxesColumnIncreasing,X} from 'lucide-react';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Checkbox} from '@/components/ui/checkbox';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import plumes from '@/public/data/investigation-plumes/manifest.json';
import {Header} from './header';
import {Locator} from './locator';
import {useEvidenceTools} from './use-evidence-tools';
import {useSnapshot} from './use-snapshot';
import {assess,canonicalInput,dateCounts,dateLabel,findings,selectObservations} from '@/lib/plume/evidence';
import type {Observation,Snapshot,Case} from '@/lib/plume/types';

const EvidenceMap=dynamic(()=>import('./evidence-map'),{ssr:false,loading:()=> <div className="map-loading"><LoaderCircle className="spin"/> Preparing the evidence map…</div>});
type Panel='evidence'|'lineage'|'quantity'|'comparison'|'notes'|'brief'|'places'|'cases'|null;
export default function Workspace({caseId}:{caseId?:string}){
 const {snapshot,error}=useSnapshot();
 if(error)return <><Header/><main className="error-page"><Info/><h1>The snapshot is unavailable</h1><p>{error}</p><button className="pill primary" onClick={()=>location.reload()}>Try again</button></main></>;
 if(!snapshot)return <><Header/><main className="error-page"><LoaderCircle className="spin"/><p>Opening the published observations…</p></main></>;
 const c=snapshot.cases.find(c=>c.id===(caseId||snapshot.cases[0].id));
 if(!c)return <><Header/><main className="error-page"><h1>Investigation not included</h1><p>This link does not resolve to an investigation in the frozen snapshot.</p><Link className="pill primary" href="/explore">Browse available cases</Link></main></>;
 return <Investigation key={c.id} snapshot={snapshot} caseData={c}/>;
}
function Investigation({snapshot,caseData:c}:{snapshot:Snapshot;caseData:Case}){
 const observations=useMemo(()=>selectObservations(snapshot,c.id),[snapshot,c.id]);
 const [index,setIndex]=useState(0),[compareIndex,setCompareIndex]=useState(Math.max(1,observations.length-1)),[mode,setMode]=useState('map');
 const [selected,setSelected]=useState(observations.map(o=>o.id)),[notes,setNotes]=useState(''),[saved,setSaved]=useState(false),[hydrated,setHydrated]=useState(false);
 const [storageError,setStorageError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[repeated,setRepeated]=useState(false);
 const [panel,setPanel]=useState<Panel>(null),[claimId,setClaimId]=useState('detection-dates'),[playing,setPlaying]=useState(false),[frameReady,setFrameReady]=useState(false);
 const [sensorPixels,setSensorPixels]=useState(false),[showScene,setShowScene]=useState(false),[methane,setMethane]=useState(true);
 const [facilities,setFacilities]=useState(true),[clearOpen,setClearOpen]=useState(false),[includeNotes,setIncludeNotes]=useState(false);
 const [camera,setCamera]=useState<{center:[number,number];zoom:number}>(),[busy,setBusy]=useState(false),[pdfUrl,setPdfUrl]=useState(''),[exportError,setExportError]=useState(''),[fingerprint,setFingerprint]=useState('');
 const [dateFrom,setDateFrom]=useState(''),[dateTo,setDateTo]=useState('');
 const workerRef=useRef<Worker|null>(null),pdfRef=useRef('');
 const o=observations[index],other=observations[Math.min(compareIndex,observations.length-1)];
 const chosen=useMemo(()=>observations.filter(o=>selected.includes(o.id)),[observations,selected]);
 const claims=findings(c,chosen),counts=dateCounts(chosen),fullCounts=dateCounts(observations),assessment=assess(c,chosen);
 const relationships=snapshot.relationships.filter(r=>c.observationIds.includes(r.observationId));
 useEvidenceTools({snapshot,caseData:c,observations,selected,claims,select:setSelected,openBrief:()=>{setIncludeNotes(false);setPanel('brief');}});
 const activeClaim=claims.find(cl=>cl.id===claimId)||claims[0];
 const visibleObs=observations.filter(o=>(!dateFrom||o.date.slice(0,10)>=dateFrom)&&(!dateTo||o.date.slice(0,10)<=dateTo));
 const visibleIndices=visibleObs.map(v=>observations.indexOf(v));
 const visibleCases=snapshot.cases.filter(k=>(k.place+' '+k.title+' '+k.country).toLowerCase().includes(query.toLowerCase())&&(!repeated||dateCounts(selectObservations(snapshot,k.id)).days>1));
 useEffect(()=>{
  const params=new URLSearchParams(location.search);if(params.has('snapshot')&&params.get('snapshot')!==snapshot.id){setNotice('The requested snapshot is unavailable. This page shows the explicitly labeled current snapshot.');}
  try{const item=localStorage.getItem('plume:'+snapshot.id+':'+c.id);if(item){const state=JSON.parse(item);if(Array.isArray(state.selected))setSelected(state.selected.filter((id:unknown)=>typeof id==='string'&&c.observationIds.includes(id)));if(typeof state.notes==='string')setNotes(state.notes.slice(0,20000));setSaved(!!state.saved);}}catch{setStorageError('Browser storage is unavailable. Your work lasts for this session; download a brief to keep it.');}
  if(params.has('evidence')){const requested=(params.get('evidence')||'').split(',').filter(Boolean);setSelected([...new Set(requested)].filter(id=>c.observationIds.includes(id)));if(requested.some(id=>!c.observationIds.includes(id)))setNotice('Some linked observations are unavailable in this case. They were excluded from the selected evidence.');}
  if(params.has('observation')){const i=observations.findIndex(o=>o.id===params.get('observation'));if(i>=0)setIndex(i);else setNotice('That observation is not included. Showing the first acquisition in this case.');}
  if(params.has('comparison')){const ci=observations.findIndex(o=>o.id===params.get('comparison'));if(ci>=0)setCompareIndex(ci);}
  const m=params.get('view');if(m&&['map','compare','list'].includes(m))setMode(m);
  setHydrated(true);
 },[c,observations,snapshot.id]);
 useEffect(()=>{if(!hydrated)return;try{localStorage.setItem('plume:'+snapshot.id+':'+c.id,JSON.stringify({version:1,selected,notes,saved}));}catch{setStorageError('Unable to save on this device. Session work and exports remain available.');}},[selected,notes,saved,hydrated,c.id,snapshot.id]);
 useEffect(()=>{if(!visibleObs.length)return;if(!visibleIndices.includes(index))setIndex(visibleIndices[0]);if(!visibleIndices.includes(compareIndex)||compareIndex===index)setCompareIndex(visibleIndices.find(i=>i!==index)??visibleIndices[0]);},[dateFrom,dateTo,index,compareIndex]);
 useEffect(()=>{setFrameReady(false);const image=new Image();let cancelled=false;image.onload=()=>{if(!cancelled)setFrameReady(true);};image.onerror=()=>{setPlaying(false);};image.src=o.asset.url;return()=>{cancelled=true;};},[o]);
 useEffect(()=>{if(!playing||!frameReady)return;const timer=setTimeout(()=>{const next=visibleIndices.find(i=>i>index);if(next===undefined){setPlaying(false);return;}setIndex(next);},1800);return()=>clearTimeout(timer);},[playing,frameReady,index,observations.length,dateFrom,dateTo]);
 useEffect(()=>{const stop=()=>{if(document.hidden)setPlaying(false);};document.addEventListener('visibilitychange',stop);return()=>document.removeEventListener('visibilitychange',stop);},[]);
 useEffect(()=>()=>{workerRef.current?.terminate();if(pdfRef.current)URL.revokeObjectURL(pdfRef.current);},[]);
 useEffect(()=>{workerRef.current?.terminate();setBusy(false);if(pdfRef.current){URL.revokeObjectURL(pdfRef.current);pdfRef.current='';setPdfUrl('');setFingerprint('');}},[selected,notes,includeNotes]);
 function selectDate(i:number){setPlaying(false);setIndex(i);if(i===compareIndex)setCompareIndex(i===observations.length-1?0:observations.length-1);}
 function toggle(id:string){setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);}
 async function share(){const url=new URL('/investigations/'+c.id,location.origin);url.searchParams.set('snapshot',snapshot.id);url.searchParams.set('observation',o.id);url.searchParams.set('evidence',[...selected].sort().join(','));url.searchParams.set('view',mode);if(mode==='compare')url.searchParams.set('comparison',other.id);try{await navigator.clipboard.writeText(url.toString());setNotice('Public evidence link copied. Your notes are not included.');}catch{setNotice('Public link: '+url.toString());}}
 function exportBrief(kind:'pdf'|'zip'){
   setBusy(true);setExportError('');workerRef.current?.terminate();const worker=new Worker('/workers/export.js',{type:'module'});workerRef.current=worker;
   const input=canonicalInput(snapshot,c,selected,notes,includeNotes);
   worker.onmessage=event=>{const result=event.data;setBusy(false);if(result.error){setExportError(result.error);worker.terminate();return;}const blob=new Blob([result.bytes],{type:kind==='pdf'?'application/pdf':'application/zip'});const url=URL.createObjectURL(blob);setFingerprint(result.fingerprint);if(kind==='pdf'){if(pdfRef.current)URL.revokeObjectURL(pdfRef.current);pdfRef.current=url;setPdfUrl(url);}else{const link=document.createElement('a');link.href=url;link.download=`plume-${c.id}-${snapshot.retrievedAt}.zip`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}worker.terminate();};
   worker.onerror=event=>{console.error('Report worker failed:',event.message);setBusy(false);setExportError('The report could not be generated. Your evidence and notes are preserved; retry the export.');worker.terminate();};worker.postMessage({snapshot,input,kind,origin:location.origin});
 }
 const caseList=<><div className="rail-heading"><p className="eyebrow">INCLUDED INVESTIGATIONS</p><h2>{c.place}</h2><p>Explore dated methane observations<br/>and the evidence behind them.</p></div><label className="case-search"><Search size={16}/><input aria-label="Search included cases" placeholder="Search included cases" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Clear case search" onClick={()=>setQuery('')}><X size={14}/></button>}</label><button className="place-action" onClick={()=>setPanel('places')}><MapPin size={15}/> Find a city or US ZIP <ArrowUpRight size={14}/></button><div className="rail-rule"/><div className="case-list">{visibleCases.map(k=>{const ko=snapshot.observations.find(o=>o.id===k.observationIds[0])!;return <Link href={'/investigations/'+k.id} key={k.id} className={'case-tile '+(k.id===c.id?'active':'')} aria-current={k.id===c.id?'page':undefined}><div className="case-thumbnail"><img src={plumes[ko.id as keyof typeof plumes].previewUrl} alt=""/></div><div><span>{k.country}</span><h3>{k.place.replace(/, (Yemen|California)$/,'')}</h3><p>{dateCounts(selectObservations(snapshot,k.id)).days} observation dates · {ko.instrument}</p></div>{k.id===c.id&&<span className="case-selected"/>}</Link>;})}{!visibleCases.length&&<div className="empty-state"><p>No included cases match these filters.</p><button onClick={()=>{setQuery('');setRepeated(false);}}>Reset filters</button></div>}</div><div className="rail-rule"/><label className="check-row"><Checkbox checked={repeated} onCheckedChange={v=>setRepeated(v===true)}/> Repeated detections only</label><div className="rail-foot"><Info size={17}/><p>A curated snapshot,<br/>not a live emissions monitor.<Link href="/method#coverage">Understand the coverage <ArrowUpRight size={12}/></Link></p></div></>;
 return <div className="application investigation-application"><Header place={c.place} onSearch={()=>setPanel('places')}/><div className="workspace-art" aria-hidden="true"/><main className={"workspace investigation-workspace view-"+mode}>
  <aside className="case-rail" aria-label="Investigations">{caseList}   <details className="date-filter-disclosure"><summary><SlidersHorizontal size={13}/> Date range {dateFrom||dateTo?'· filtered':'· all included dates'}</summary><div className="list-filters"><label>From<input type="date" aria-label="Filter observations from" value={dateFrom} onChange={e=>{setPlaying(false);setDateFrom(e.target.value);}}/></label><label>To<input type="date" aria-label="Filter observations to" value={dateTo} onChange={e=>{setPlaying(false);setDateTo(e.target.value);}}/></label><button onClick={()=>{setDateFrom('');setDateTo('');}}>Reset dates</button></div><p>Filters browsing in both views. The case timeline and brief selection remain visible.</p></details><div className="workspace-layers"><h3><Layers3 size={17}/> Map layers</h3><label><Checkbox checked={methane} onCheckedChange={v=>setMethane(v===true)}/> Methane enhancement</label><label><Checkbox checked={sensorPixels} onCheckedChange={v=>setSensorPixels(v===true)}/> Inspect sensor pixels</label><label><Checkbox checked={showScene} onCheckedChange={v=>setShowScene(v===true)}/> Full acquisition scene</label><label><Checkbox checked={facilities} onCheckedChange={v=>setFacilities(v===true)}/> Registered infrastructure</label></div><div className="rail-measurement"><span className="eyebrow">THE MAP MEASURES</span><h3>Methane enhancement</h3><p>Column enhancement · ppm·m</p><div className={showScene?"cividis":"inferno-scale"}/><div className="legend-values"><span>0</span><span>{o.asset.scale[1].toLocaleString()}</span></div><p className="legend-explanation"><Info size={15}/> {!showScene&&!sensorPixels?'Derived contour bands; interpolated within measured cells.':'Original sensor samples.'} Empty areas are not measured zeros.</p></div></aside>
  <section className="investigation-center">
   <div className="case-topline"><div><button className="mobile-cases" onClick={()=>setPanel('cases')}><List size={16}/> Cases</button><span className="eyebrow">Showing observations for</span><h1>{c.place}</h1><p>{fullCounts.days} recorded dates <span>·</span> {dateLabel(observations[0].date,true)} — {dateLabel(observations.at(-1)!.date,true)}</p></div><button className="icon-button share-button" onClick={share} aria-label="Copy public evidence link"><Share2 size={18}/></button></div>
<div className="map-toolbar"><Tabs value={mode} onValueChange={m=>{setMode(m);setPlaying(false);setCamera(undefined);}}><TabsList className="map-tabs"><TabsTrigger value="map"><MapIcon size={15}/>Observation</TabsTrigger><TabsTrigger value="compare" disabled={visibleObs.length<2}><SplitSquareHorizontal size={15}/>Compare dates</TabsTrigger><TabsTrigger value="list"><List size={15}/>Evidence list</TabsTrigger></TabsList></Tabs><button className="toolbar-source" onClick={()=>setPanel('quantity')}>{o.provider} <ArrowUpRight size={13}/></button></div>
   <div className={'map-stage '+(mode==='compare'?'compare-stage':'')}>
    {mode==='list'?<div className="evidence-list">{visibleObs.map(obs=><article className={'observation-row '+(activeClaim.evidenceIds.includes(obs.id)&&panel==='evidence'?'evidence-highlight':'')} key={obs.id}><img src={plumes[obs.id as keyof typeof plumes].previewUrl} alt={`Derived enhancement contours, ${dateLabel(obs.date)}`}/><div><p className="eyebrow">{obs.provider} / {obs.instrument}</p><h3>{dateLabel(obs.date,true)}</h3><p>Column enhancement · ppm·m</p><button className="text-link" onClick={()=>{selectDate(observations.indexOf(obs));setMode('map');}}>Inspect this observation <ArrowRight size={13}/></button></div><Checkbox aria-label={`Include ${dateLabel(obs.date,true)} in brief`} checked={selected.includes(obs.id)} onCheckedChange={()=>toggle(obs.id)}/></article>)}{!visibleObs.length&&<div className="empty-state"><h3>No observations in this date range</h3><p>This does not establish that methane emissions were absent.</p></div>}</div>:!visibleObs.length?<div className="empty-state map-empty"><Info/><h3>No observations in this date range</h3><p>This does not establish that methane emissions were absent.</p><button onClick={()=>{setDateFrom('');setDateTo('');}}>Reset dates</button></div>:<><EvidenceMap key={mode+'-a'} observation={o} allObservations={observations} caseData={c} highlight={panel==='evidence'&&activeClaim.evidenceIds.includes(o.id)} showFacilities={facilities} showScene={showScene} sensorPixels={sensorPixels} showMethane={methane} immersive={mode==='map'} camera={mode==='compare'?camera:undefined} onCamera={mode==='compare'?setCamera:undefined}/>{mode==='compare'&&visibleObs.length>1&&<EvidenceMap key={mode+'-b'} observation={other} allObservations={observations} caseData={c} showFacilities={facilities} showScene={showScene} sensorPixels={sensorPixels} showMethane={methane} camera={camera} onCamera={setCamera}/>}<Locator location={c.location} place={c.country}/></>}
   </div>
   {mode==='compare'&&visibleObs.length>1&&<div className="compare-selectors"><label>Observation A<select value={index} onChange={e=>selectDate(Number(e.target.value))}>{visibleObs.map(o=>{const i=observations.indexOf(o);return <option key={o.id} value={i} disabled={i===compareIndex}>{dateLabel(o.date,true)}</option>;})}</select></label><span>Same enhancement scale. Brightness is not an emission-rate comparison.</span><label>Observation B<select value={compareIndex} onChange={e=>setCompareIndex(Number(e.target.value))}>{visibleObs.map(o=>{const i=observations.indexOf(o);return <option key={o.id} value={i} disabled={i===index}>{dateLabel(o.date,true)}</option>;})}</select></label></div>}
   <section className="timeline" aria-label="Acquisition timeline"><div className="timeline-head"><div><span className="eyebrow">OBSERVATIONS THROUGH TIME</span><span className="timeline-count">{fullCounts.acquisitions} distinct acquisitions</span></div><div className="play-controls"><button aria-label="Previous acquisition" disabled={!visibleIndices.some(i=>i<index)} onClick={()=>selectDate(visibleIndices.filter(i=>i<index).at(-1)!)}><ChevronLeft size={17}/></button><button aria-label={playing?'Pause replay':'Play acquisitions'} disabled={!visibleObs.length} onClick={()=>{if(index===visibleIndices.at(-1))setIndex(visibleIndices[0]);setPlaying(!playing);}}>{playing?<Pause size={15}/>:<Play size={15}/>}</button><button aria-label="Next acquisition" disabled={!visibleIndices.some(i=>i>index)} onClick={()=>selectDate(visibleIndices.find(i=>i>index)!)}><ChevronRight size={17}/></button></div></div><div className="timeline-track"><span className="track-instrument">{o.instrument}</span><div className="track-line"/>{observations.map((obs,i)=>{const first=Date.parse(observations[0].date),last=Date.parse(observations.at(-1)!.date);const position=10+(last===first?0:(Date.parse(obs.date)-first)/(last-first))*80;return <button key={obs.id} className={'timeline-point '+(i===index?'current':'')+' '+(selected.includes(obs.id)?'included':'excluded')+' '+(panel==='evidence'&&activeClaim.evidenceIds.includes(obs.id)?'claim-supported':'')} style={{left:position+'%'}} onClick={()=>selectDate(i)} aria-label={`View ${dateLabel(obs.date,true)}`} aria-pressed={i===index} disabled={!visibleIndices.includes(i)}><span className="point-dot"/><span>{dateLabel(obs.date,true)}</span></button>;})}</div><p className="timeline-note"><Info size={12}/> Gaps mean no included record. They do not show an absence of methane.</p></section>
  </section>
  <aside className="findings-panel" aria-label="Investigation findings"><div className="panel-title"><button className="panel-back" onClick={()=>setPanel('cases')}><ArrowLeft size={16}/> All investigations</button><div className="observation-arrows"><button aria-label="Previous observation" disabled={index===0} onClick={()=>selectDate(index-1)}><ChevronLeft size={17}/></button><button aria-label="Next observation" disabled={index===observations.length-1} onClick={()=>selectDate(index+1)}><ChevronRight size={17}/></button></div><button className={'icon-button '+(saved?'is-saved':'')} aria-label={saved?'Unsave investigation':'Save investigation on this device'} onClick={()=>{setSaved(!saved);setNotice(saved?'Investigation removed from saved cases.':'Investigation saved on this device.');}}><Bookmark size={18} fill={saved?'currentColor':'none'}/></button></div><div className="selected-observation-preview"><img src={plumes[o.id as keyof typeof plumes].previewUrl} alt={`Selected methane enhancement observation, ${dateLabel(o.date,true)}`}/><span>{dateLabel(o.date,true)} · {o.instrument}</span></div><h2>{c.id==='newby-island'?'Newby Island observation':'Marib methane observation'}</h2><p className="observation-place"><MapPin size={14}/>{c.place}</p><div className="observation-facts"><button onClick={()=>setPanel('quantity')}><ChartNoAxesColumnIncreasing size={19}/><span>Plume rate<small>Single acquisition · provider estimate</small></span><strong>{o.rate===null?'Not provided':(o.rate/1000).toFixed(2)+' t/hr'}{o.uncertainty!==null&&<small>± {(o.uncertainty/1000).toFixed(2)} t/hr</small>}</strong></button><button onClick={()=>setPanel('comparison')}><MapPin size={18}/><span>Source attribution</span><strong className="fact-status">Unresolved</strong></button></div><p className="selection-scope">From {chosen.length} selected observations · {counts.days} dates</p>
   <div className="findings">{claims.map(cl=><button className={'finding '+cl.kind} key={cl.id} onClick={()=>{setClaimId(cl.id);setPanel('evidence');}}><span className="finding-label">{cl.kind==='established'?<CheckCheck size={15}/>:cl.kind==='unresolved'?<Info size={15}/>:<ArrowRight size={15}/>} {cl.kind==='established'?'ESTABLISHED':cl.kind==='unresolved'?'UNRESOLVED':'NEXT EVIDENCE STEP'}<ArrowUpRight size={13}/></span><p>{cl.kind==='established'&&counts.days>1?`Detected on ${counts.days} dates, from ${dateLabel(chosen[0].date,true)} to ${dateLabel(chosen.at(-1)!.date,true)}.`:cl.kind==='unresolved'&&chosen.length?'Continuous emissions and the emitting source remain unresolved.':cl.text}</p></button>)}</div>
   <details className="evidence-checks"><summary><ShieldCheck size={15}/> Evidence checks <ChevronRight size={14}/></summary><div className="status-strip" aria-label="Evidence statuses"><button onClick={()=>setPanel('quantity')}>Quality <span>{o.quality||'Not supplied'}</span></button><button onClick={()=>setPanel('lineage')}>Lineage <span>{relationships.length?'Products linked':'Recorded'}</span></button><button onClick={()=>setPanel('evidence')}>Recurrence <span>{counts.days} dates</span></button><button onClick={()=>setPanel('comparison')}>Attribution <span>Unresolved</span></button><button onClick={()=>setPanel('comparison')}>Comparison <span>Withheld</span></button></div></details>
   <div className="evidence-actions"><button onClick={()=>setPanel('lineage')}><Layers3 size={17}/><span>Follow the record trail<small>{relationships.length?`${relationships.length} related products · inspect what counts`:'Inspect the original observations'}</small></span><ChevronRight size={15}/></button><button onClick={()=>setPanel('comparison')}><ShieldCheck size={17}/><span>Can these figures be compared?<small>Read the comparison assessment</small></span><ChevronRight size={15}/></button></div>
   <div className="brief-actions"><button className="pill primary" disabled={!selected.length} title={!selected.length?'Select at least one observation to create a brief':undefined} onClick={()=>setPanel('brief')}><FileText size={17}/> Create investigation brief <ArrowRight size={17}/></button><button className="notes-button" onClick={()=>setPanel('notes')}><StickyNote size={15}/>{notes?'Edit your notes':'Add a note'}<span>On this device</span></button></div><p className="panel-credit">Source: <a href="https://carbonmapper.org/terms" target="_blank" rel="noreferrer">Carbon Mapper</a> · <Link href="/method">Method & limitations</Link></p>
  </aside>
 </main>
 {notice&&<div className="notice" role="status"><span>{notice}</span><button aria-label="Dismiss message" onClick={()=>setNotice('')}><X size={15}/></button></div>}{storageError&&<div className="storage-warning" role="status">{storageError}</div>}
 <Sheet open={!!panel} onOpenChange={v=>{if(!v)setPanel(null);}}><SheetContent className={'plume-sheet '+(panel==='brief'?'brief-sheet':'')}><SheetHeader><SheetTitle>{panel==='evidence'?'Behind the finding':panel==='lineage'?'One observation. Several records.':panel==='quantity'?'The measurement, in context':panel==='comparison'?'Can these figures be compared?':panel==='notes'?'Your investigation notes':panel==='brief'?'Create your investigation brief':panel==='places'?'Find a place':'Included investigations'}</SheetTitle><SheetDescription>{panel==='brief'?'Choose the evidence, then take a verifiable copy with you.':panel==='notes'?'Private, plain-text notes saved on this device.':panel==='places'?'Place lookup and methane coverage are separate.':'Every conclusion has a scope. Every record has a source.'}</SheetDescription></SheetHeader>
  <div className="sheet-body">
  {panel==='cases'&&caseList}
  {panel==='places'&&<PlaceLookup snapshot={snapshot} onNotice={setNotice}/>}
  {panel==='evidence'&&<><div className="quoted-finding"><span className="eyebrow">{activeClaim.kind}</span><h3>{activeClaim.text}</h3></div><p className="body-note">Scope: selected evidence in this geographic area. Highlighted observations support this finding.</p><Selection observations={observations} selected={selected} toggle={toggle}/><div className="rule-detail"><strong>How this finding is produced</strong><p>{activeClaim.rule==='distinct-utc-detection-days-v1'?'Unique acquisition dates are counted after known product relationships are resolved. Multiple publications do not add detection days.':'This rule states an evidence limitation or a recommended next step; it is not a measured emissions result.'}</p><code>{activeClaim.rule}</code></div></>}
  {panel==='lineage'&&<><div className="lineage-summary"><span>{relationships.length||observations.length}</span><ArrowRight/><span>{relationships.length?'1':fullCounts.acquisitions}</span><p>{relationships.length?'product/version records for one plume observation':'distinct included acquisitions'}</p></div><p className="body-note">{relationships.length?'These records share the same plume identifier. They provide different products and processing revisions. They do not represent additional acquisition dates.':'Open the individual records to inspect their published acquisition and product metadata.'}</p>{relationships.map(r=><a className="record-card" key={r.id} href={r.sourceUrl} target="_blank" rel="noreferrer"><span className="record-icon"><Layers3 size={18}/></span><div><strong>{r.role}</strong><code>{r.collection}</code><span>{r.observationId}</span></div><ExternalLink size={14}/></a>)}{!relationships.length&&observations.map(obs=><SourceRecord key={obs.id} observation={obs}/>)}<div className="attention-box"><Info size={18}/><p>Processing revisions can change a published estimate. That is not evidence of a change in atmospheric emissions.</p></div><h3 className="sheet-section-title">Across publishers</h3><p>NASA/Carbon Mapper matching candidates remain unresolved. This release does not count a candidate match as verified corroboration.</p></>}
  {panel==='quantity'&&<><div className="measurement-preview"><img src={o.asset.url} alt={`Dated enhancement image, ${dateLabel(o.date)}`}/><span>{dateLabel(o.date,true)}</span></div><h3 className="sheet-section-title">Methane column enhancement</h3><p>Excess methane along the instrument’s atmospheric column, measured in <strong>ppm·m</strong>. This is the quantity shown by the map colors.</p><dl className="details-grid"><dt>Color scale</dt><dd>0–{o.asset.scale[1].toLocaleString()} ppm·m</dd><dt>Valid-pixel maximum</dt><dd>{Math.round(o.asset.max).toLocaleString()} ppm·m</dd><dt>Instrument / publisher</dt><dd>{o.instrument} / {o.provider}</dd><dt>Acquisition UTC</dt><dd>{o.date}</dd><dt>Location meaning</dt><dd>{o.locationRole}</dd><dt>Provider quality</dt><dd>{o.quality||'Not supplied'}</dd><dt>Processing software</dt><dd>{o.processing}</dd><dt>Native CRS</dt><dd>{o.asset.nativeCrs}</dd></dl><h3 className="sheet-section-title">Plume rate, single acquisition</h3><div className="quantity-value">{o.rate===null?o.rateStatus==='suppressed'?'Rate withheld by provider':'Rate not provided':`${Math.round(o.rate).toLocaleString()} kg/h`}</div>{o.uncertainty!==null&&<p>Provider-reported uncertainty: ±{Math.round(o.uncertainty).toLocaleString()} kg/h.</p>}<p className="body-note">{o.uncertaintyDefinition}. This quantity is separate from the image’s ppm·m scale.</p><div className="attention-box"><Info size={18}/><p>These estimates describe separate moments. A difference between them does not establish a change in ongoing emissions.</p></div><SourceRecord observation={o}/></>}
  {panel==='comparison'&&<><div className="comparison-context"><div><span className="eyebrow">OBSERVED CONTEXT</span><h3>{chosen.length} selected acquisitions</h3><p>Published plume estimates describe individual observation moments.</p></div><div><span className="eyebrow">REPORTED CONTEXT</span><h3>{c.inventory?`${c.inventory.value.toLocaleString()} ${c.inventory.unit}`:'No annual record included'}</h3><p>{c.inventory?`${c.inventory.facility} · ${c.inventory.year} · ${c.inventory.gas}`:'No relevant annual facility report is included for this geographic case.'}</p>{c.inventory&&<a href={c.inventory.sourceUrl} target="_blank" rel="noreferrer" className="text-link">Original EPA reporting source <ExternalLink size={13}/></a>}</div></div><div className="withheld"><ShieldCheck/><div><strong>Numerical comparison withheld</strong><p>Individual satellite observations do not establish annual methane mass.</p></div></div>{c.attributionContext&&<div className="attribution-context"><span className="eyebrow">A PLACE IS NOT A PROCESS</span><h3>Landfill or composting?</h3><p>{c.attributionContext}</p><a href={c.contextSource} target="_blank" rel="noreferrer" className="text-link">Inspect the permitted source list <ExternalLink size={13}/></a></div>}<div className="assessment-checks">{assessment.map(a=><div className={'assessment-row '+a.status} key={a.id}><span>{a.status==='satisfied'?<Check size={15}/>:a.status==='failed'?<X size={15}/>:<Info size={15}/>}</span><div><strong>{a.label}<small>{a.status.replace('_',' ')}</small></strong><p>{a.reason}</p></div></div>)}</div>{c.facilities?.length&&<><h3 className="sheet-section-title">Nearby registered infrastructure</h3><label className="check-row"><Checkbox checked={facilities} onCheckedChange={v=>setFacilities(v===true)}/> Show registry locations on map</label>{c.facilities.map(f=><a className="record-card" href={f.sourceUrl} key={f.id} target="_blank" rel="noreferrer"><MapPin size={19}/><div><strong>{f.name}</strong><span>{f.relationship}</span><small>{f.role}</small></div><ExternalLink size={14}/></a>)}</>}<p className="body-note">Next evidence step: review source attribution, reporting boundaries, and an appropriate time-integrated estimate. Additional isolated observations alone do not resolve the annual comparison.</p></>}
  {panel==='notes'&&<><label className="notes-label" htmlFor="case-notes">Your notes</label><textarea id="case-notes" className="notes-textarea" value={notes} maxLength={20000} onChange={e=>setNotes(e.target.value)} placeholder="Questions to investigate, records to request, or observations of your own…"/><p className="body-note">{notes.length.toLocaleString()} / 20,000 characters. Notes are not verified findings. Public links never contain them.</p><button className="pill primary" onClick={()=>{setSaved(true);setNotice('Notes saved on this device.');setPanel(null);}}>Save notes <Check size={16}/></button><button className="clear-button" onClick={()=>setClearOpen(true)}>Clear this device’s case notes and selection</button></>}
  {panel==='brief'&&<><div className="brief-summary"><span className="eyebrow">{c.place}</span><h3>The evidence you choose.<br/>The context that stays.</h3><p>PDF brief + a machine-readable evidence package.</p></div><Selection observations={observations} selected={selected} toggle={toggle}/><label className="check-row notes-include"><Checkbox checked={includeNotes} onCheckedChange={v=>setIncludeNotes(v===true)}/> Include my notes in this download</label><p className="body-note">{counts.days} {counts.days===1?'date':'dates'} selected. Findings recompute from this selection. Data terms and source links travel with the report.</p><div className="export-controls"><button className="pill primary" disabled={!selected.length||busy} onClick={()=>exportBrief('pdf')}>{busy?<LoaderCircle className="spin" size={17}/>:<FileText size={17}/>} Generate PDF preview</button><button className="pill" disabled={!selected.length||busy} onClick={()=>exportBrief('zip')}><Download size={17}/> Download evidence ZIP</button></div>{busy&&<p role="status" className="body-note">Preparing your selected evidence on this device…</p>}{exportError&&<p role="alert" className="attention-box">{exportError}</p>}{pdfUrl&&<><a className="pill primary download-pdf" href={pdfUrl} download={`plume-${c.id}.pdf`}><Download size={16}/> Download PDF</a><iframe className="pdf-preview" src={pdfUrl} title="Generated investigation PDF preview"/><p className="body-note">Evidence fingerprint <code>{fingerprint.slice(0,20)}…</code></p></>}</>}
  </div>
 </SheetContent></Sheet>
 <AlertDialog open={clearOpen} onOpenChange={setClearOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Clear this case’s local work?</AlertDialogTitle><AlertDialogDescription>This removes your device-local notes and resets the evidence selection. Published observations are unaffected.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep my work</AlertDialogCancel><AlertDialogAction onClick={()=>{setNotes('');setSelected(observations.map(o=>o.id));setSaved(false);setNotice('Local case work cleared.');}}>Clear local work</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
function SourceRecord({observation:o}:{observation:Observation}){return <a className="record-card" href={o.sourceUrl} target="_blank" rel="noreferrer"><ExternalLink size={18}/><div><strong>View original provider record</strong><code>{o.id}</code><span>{o.provider} · {dateLabel(o.date,true)}</span></div><ArrowUpRight size={15}/></a>}
function Selection({observations,selected,toggle}:{observations:Observation[];selected:string[];toggle:(id:string)=>void}){return <div className="evidence-selection">{observations.map(o=><label key={o.id} className="selection-row"><Checkbox checked={selected.includes(o.id)} onCheckedChange={()=>toggle(o.id)} aria-label={`Include ${dateLabel(o.date,true)} in brief`}/><img src={o.asset.url} alt=""/><span><strong>{dateLabel(o.date,true)}</strong><small>{o.instrument} · {o.provider}</small></span><a href={o.sourceUrl} target="_blank" rel="noreferrer" aria-label={`Original record for ${dateLabel(o.date,true)}`}><ExternalLink size={14}/></a></label>)}</div>}
function PlaceLookup({snapshot,onNotice}:{snapshot:Snapshot;onNotice:(text:string)=>void}){return <PlaceSearch snapshot={snapshot} onNotice={onNotice}/>}
import {PlaceSearch} from './place-search';
